// Generated by CoffeeScript 1.6.3
(function() {
  var getPositions, isLocalStorage, markyBtn, savePosition;

  isLocalStorage = localStorage ? true : false;

  markyBtn = document.getElementById("marky-btn");

  if (isLocalStorage && !markyBtn) {
    Object.size = function(obj) {
      var key, size, _i, _len;
      size = 0;
      for (_i = 0, _len = obj.length; _i < _len; _i++) {
        key = obj[_i];
        if (obj.hasOwnProperty(key)) {
          size++;
        }
      }
      return size;
    };
    markyBtn.onclick = function(e) {
      var scrollPos;
      e.preventDefault();
      scrollPos = document.body.scrollTop;
      savePosition(scrollPos);
    };
    savePosition = function(pos) {
      var markyStore, now, obj;
      now = new Date().toString();
      obj = {};
      obj[now] = pos;
      if (localStorage.getItem("marky-btn")) {
        markyStore = JSON.parse(localStorage.getItem("marky-btn"));
        markyStore[now] = pos;
      }
      if (markyStore) {
        obj = markyStore;
      }
      localStorage.setItem("marky-btn", JSON.stringify(obj));
    };
    getPositions = function() {
      return JSON.parse(localStorage.getItem("marky-btn"));
    };
  }

}).call(this);
