// Generated by CoffeeScript 1.6.3
(function() {
  var documentHeight, getPositions, hasLocalStorage, markyBtn, markyBtnDom, markyTextDiv, renderPositions, savePosition, windowHeight;

  hasLocalStorage = localStorage ? true : false;

  markyBtn = document.getElementById("marky-btn");

  if (hasLocalStorage && !markyBtn) {
    markyBtnDom = document.createElement('a');
    markyBtnDom.id = 'marky-btn';
    markyBtnDom.href = '#';
    markyBtnDom.innerHTML = 'mark!';
    document.getElementsByTagName('body')[0].appendChild(markyBtnDom);
    markyTextDiv = document.createElement('div');
    markyTextDiv.id = 'marky-text-container';
    markyTextDiv.innerHTML = '<input type="text" id="marky-text">';
    document.getElementsByTagName('body')[0].appendChild(markyTextDiv);
    markyBtn = document.getElementById("marky-btn");
    documentHeight = document.height;
    windowHeight = window.innerHeight;
    Object.size = function(obj) {
      var key, size, _i, _len;
      size = 0;
      for (_i = 0, _len = obj.length; _i < _len; _i++) {
        key = obj[_i];
        if (obj.hasOwnProperty(key)) {
          size++;
        }
      }
      return size;
    };
    markyBtn.onclick = function(e) {
      var scrollPos;
      e.preventDefault();
      scrollPos = document.body.scrollTop;
      this.className = "active";
      document.getElementById("marky-text-container").style.display = "block";
      savePosition(scrollPos);
    };
    savePosition = function(pos) {
      var markyStore, now, nowDateString, obj;
      now = new Date();
      nowDateString = now.getMonth() + "/" + now.getDate() + "- " + now.getHours() + ":" + now.getMinutes();
      obj = {};
      obj[pos] = nowDateString;
      if (localStorage.getItem("marky-btn")) {
        markyStore = JSON.parse(localStorage.getItem("marky-btn"));
        markyStore[pos] = nowDateString;
      }
      if (markyStore) {
        obj = markyStore;
      }
      localStorage.setItem("marky-btn", JSON.stringify(obj));
      renderPositions();
    };
    getPositions = function() {
      return JSON.parse(localStorage.getItem("marky-btn"));
    };
    renderPositions = function() {
      var markPositions, marker, markers, position, temp, top, _i, _len;
      markPositions = getPositions();
      console.log("markPositions:", markPositions);
      for (position in markPositions) {
        top = Math.floor((position / (documentHeight - windowHeight)) * windowHeight) + "px";
        console.log("percentage:", top);
        temp = document.createElement('a');
        temp.href = '#';
        temp.innerHTML = "<span>blah</span>";
        temp.className = 'marky-mark';
        temp.style.top = top;
        temp.setAttribute("data-loc", position);
        document.getElementsByTagName('body')[0].appendChild(temp);
      }
      markers = document.getElementsByClassName('marky-mark');
      for (_i = 0, _len = markers.length; _i < _len; _i++) {
        marker = markers[_i];
        marker.onclick = function(e) {
          var pos;
          e.preventDefault();
          this.className = this.className + " active";
          pos = this.getAttribute("data-loc");
          window.scrollTo(0, pos);
        };
      }
    };
    renderPositions();
  }

}).call(this);
